apiVersion: perses.dev/v1alpha1
kind: PersesDatasource
metadata:
  name: thanos-querier-datasource
  namespace: perses-dev
spec:
  display:
    name: "Thanos Querier Datasource"
  default: true
  plugin:
    kind: "PrometheusDatasource"
    spec:
      directUrl: "/api/prometheus"
