# permissions for end users to view perses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: perses-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: perses-operator
    app.kubernetes.io/part-of: perses-operator
    app.kubernetes.io/managed-by: kustomize
  name: perses-viewer-role
rules:
  - apiGroups:
      - perses.dev
    resources:
      - perses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - perses.dev
    resources:
      - perses/status
    verbs:
      - get
