apiVersion: perses.dev/v1alpha1
kind: PersesDatasource
metadata:
  labels:
    app.kubernetes.io/name: perses-datasource
    app.kubernetes.io/instance: perses-prometheus-datasource
    app.kubernetes.io/part-of: perses-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: perses-operator
  name: perses-datasource-sample
spec:
  kind: Datasource
  metadata:
    name: perses-prometheus-datasource
    project: default
    createdAt: "2021-11-09T00:00:00Z"
    updatedAt: "2021-11-09T00:00:00Z"
    version: 0
  spec:
    display:
      name: "Default Datasource"
    default: true
    plugin:
      kind: "PrometheusDatasource"
      spec:
        directUrl: "https://prometheus.demo.do.prometheus.io"
